# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/MAP/io_ports_150M.xdc

# IP: ip/fpga_bram64/fpga_bram64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_bram64 || ORIG_REF_NAME==fpga_bram64} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_78m_buff_0/design_1_clk_78m_buff_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_78m_buff_0 || ORIG_REF_NAME==design_1_clk_78m_buff_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_150m_buff_0/design_1_clk_150m_buff_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_150m_buff_0 || ORIG_REF_NAME==design_1_clk_150m_buff_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_0 || ORIG_REF_NAME==design_1_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_1_0/design_1_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_1_0 || ORIG_REF_NAME==design_1_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RESET_CTRL_0_0/design_1_RESET_CTRL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RESET_CTRL_0_0 || ORIG_REF_NAME==design_1_RESET_CTRL_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_aurora_64b66b_0_0/design_1_aurora_64b66b_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_0_0 || ORIG_REF_NAME==design_1_aurora_64b66b_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_0/design_1_aurora_64b66b_0_0_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_0_0_gt || ORIG_REF_NAME==design_1_aurora_64b66b_0_0_gt} -quiet] -quiet

# IP: bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_1/design_1_aurora_64b66b_0_0_fifo_gen_master.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_0_0_fifo_gen_master || ORIG_REF_NAME==design_1_aurora_64b66b_0_0_fifo_gen_master} -quiet] -quiet

# IP: bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_2/design_1_aurora_64b66b_0_0_fifo_gen_slave.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_0_0_fifo_gen_slave || ORIG_REF_NAME==design_1_aurora_64b66b_0_0_fifo_gen_slave} -quiet] -quiet

# IP: bd/design_1/ip/design_1_aurora_64b66b_1_0/design_1_aurora_64b66b_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_1_0 || ORIG_REF_NAME==design_1_aurora_64b66b_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_0/design_1_aurora_64b66b_1_0_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_1_0_gt || ORIG_REF_NAME==design_1_aurora_64b66b_1_0_gt} -quiet] -quiet

# IP: bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_1/design_1_aurora_64b66b_1_0_fifo_gen_master.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_1_0_fifo_gen_master || ORIG_REF_NAME==design_1_aurora_64b66b_1_0_fifo_gen_master} -quiet] -quiet

# IP: bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_2/design_1_aurora_64b66b_1_0_fifo_gen_slave.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_1_0_fifo_gen_slave || ORIG_REF_NAME==design_1_aurora_64b66b_1_0_fifo_gen_slave} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_2_0/design_1_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_2_0 || ORIG_REF_NAME==design_1_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_3_0/design_1_util_ds_buf_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_3_0 || ORIG_REF_NAME==design_1_util_ds_buf_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_HEARTBEAT_0_0/design_1_HEARTBEAT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_HEARTBEAT_0_0 || ORIG_REF_NAME==design_1_HEARTBEAT_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_emax6_0_0/design_1_emax6_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_emax6_0_0 || ORIG_REF_NAME==design_1_emax6_0_0} -quiet] -quiet

# IP: ip/fpga_bram64/fpga_bram64.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_bram64 || ORIG_REF_NAME==fpga_bram64} -quiet] -quiet

# IP: bd/design_1/ip/design_1_C2C_SLAVE_TOP_0_0/design_1_C2C_SLAVE_TOP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_C2C_SLAVE_TOP_0_0 || ORIG_REF_NAME==design_1_C2C_SLAVE_TOP_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_C2C_MASTER_TOP_0_0/design_1_C2C_MASTER_TOP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_C2C_MASTER_TOP_0_0 || ORIG_REF_NAME==design_1_C2C_MASTER_TOP_0_0} -quiet] -quiet

# XDC: ip/fpga_bram64/fpga_bram64_ooc.xdc

# XDC: bd/design_1/ip/design_1_clk_78m_buff_0/design_1_clk_78m_buff_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_78m_buff_0 || ORIG_REF_NAME==design_1_clk_78m_buff_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_78m_buff_0/design_1_clk_78m_buff_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_clk_150m_buff_0/design_1_clk_150m_buff_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_150m_buff_0 || ORIG_REF_NAME==design_1_clk_150m_buff_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_150m_buff_0/design_1_clk_150m_buff_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_0 || ORIG_REF_NAME==design_1_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_util_ds_buf_1_0/design_1_util_ds_buf_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_1_0 || ORIG_REF_NAME==design_1_util_ds_buf_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_util_ds_buf_1_0/design_1_util_ds_buf_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_0/synth/design_1_aurora_64b66b_0_0_gt_ooc.xdc

# XDC: bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_0/synth/design_1_aurora_64b66b_0_0_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_0_0_gt || ORIG_REF_NAME==design_1_aurora_64b66b_0_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_1/design_1_aurora_64b66b_0_0_fifo_gen_master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_0_0_fifo_gen_master || ORIG_REF_NAME==design_1_aurora_64b66b_0_0_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_1/design_1_aurora_64b66b_0_0_fifo_gen_master_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_0_0_fifo_gen_master || ORIG_REF_NAME==design_1_aurora_64b66b_0_0_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_2/design_1_aurora_64b66b_0_0_fifo_gen_slave.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_0_0_fifo_gen_slave || ORIG_REF_NAME==design_1_aurora_64b66b_0_0_fifo_gen_slave} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_2/design_1_aurora_64b66b_0_0_fifo_gen_slave_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_0_0_fifo_gen_slave || ORIG_REF_NAME==design_1_aurora_64b66b_0_0_fifo_gen_slave} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_0_0/design_1_aurora_64b66b_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_aurora_64b66b_0_0/design_1_aurora_64b66b_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_0_0 || ORIG_REF_NAME==design_1_aurora_64b66b_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_0_0/design_1_aurora_64b66b_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_0_0 || ORIG_REF_NAME==design_1_aurora_64b66b_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_0/synth/design_1_aurora_64b66b_1_0_gt_ooc.xdc

# XDC: bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_0/synth/design_1_aurora_64b66b_1_0_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_1_0_gt || ORIG_REF_NAME==design_1_aurora_64b66b_1_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_1/design_1_aurora_64b66b_1_0_fifo_gen_master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_1_0_fifo_gen_master || ORIG_REF_NAME==design_1_aurora_64b66b_1_0_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_1/design_1_aurora_64b66b_1_0_fifo_gen_master_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_1_0_fifo_gen_master || ORIG_REF_NAME==design_1_aurora_64b66b_1_0_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_2/design_1_aurora_64b66b_1_0_fifo_gen_slave.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_1_0_fifo_gen_slave || ORIG_REF_NAME==design_1_aurora_64b66b_1_0_fifo_gen_slave} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_2/design_1_aurora_64b66b_1_0_fifo_gen_slave_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_1_0_fifo_gen_slave || ORIG_REF_NAME==design_1_aurora_64b66b_1_0_fifo_gen_slave} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_1_0/design_1_aurora_64b66b_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_aurora_64b66b_1_0/design_1_aurora_64b66b_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_1_0 || ORIG_REF_NAME==design_1_aurora_64b66b_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_aurora_64b66b_1_0/design_1_aurora_64b66b_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_1_0 || ORIG_REF_NAME==design_1_aurora_64b66b_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_util_ds_buf_2_0/design_1_util_ds_buf_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_2_0 || ORIG_REF_NAME==design_1_util_ds_buf_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_util_ds_buf_2_0/design_1_util_ds_buf_2_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_util_ds_buf_3_0/design_1_util_ds_buf_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_3_0 || ORIG_REF_NAME==design_1_util_ds_buf_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_util_ds_buf_3_0/design_1_util_ds_buf_3_0_ooc.xdc

# XDC: ip/fpga_bram64/fpga_bram64_ooc.xdc

# XDC: bd/design_1/ip/design_1_emax6_0_0/design_1_emax6_0_0_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
