# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcvu440-flga2892-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.cache/wt [current_project]
set_property parent.project_path /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/RESET/reset_common.vh
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/common.vh
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/c2c_slave_common.vh
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/c2c_master_common.vh
}
read_verilog -library xil_defaultlib {
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/RESET/reset_ctrl.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/HEARTBEAT/heartbeat.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/bit24_booth_wallace.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/fsm.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/lmring.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/nbit_csa.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/nbit_ndepth_queue.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/nbit_register.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/stage1.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/stage2.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/stage3.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/stage4.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/stage5.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/unit.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/emax6.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/acc_ctrl.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/aurora_ctrl.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/buff_16bxnw.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/buff_578bxnw.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/fifo_128bxnw.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/fifo_16bxnw.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/fifo_578bxnw.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/rd_in.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/saxi_top.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/wr_in.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/c2c_slave_top.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/fifo_21bxnw.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/maxi_top.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/rd_out.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/wr_out.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/C2C/c2c_master_top.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
  /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/imports/RTL/vu440_top.v
}
read_ip -quiet /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/ip/fpga_bram64/fpga_bram64.xci
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/ip/fpga_bram64/fpga_bram64_ooc.xdc]

add_files /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_clk_78m_buff_0/design_1_clk_78m_buff_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_clk_78m_buff_0/design_1_clk_78m_buff_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_clk_150m_buff_0/design_1_clk_150m_buff_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_clk_150m_buff_0/design_1_clk_150m_buff_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_1_0/design_1_util_ds_buf_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_1_0/design_1_util_ds_buf_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_0/synth/design_1_aurora_64b66b_0_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_0/synth/design_1_aurora_64b66b_0_0_gt.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_1/design_1_aurora_64b66b_0_0_fifo_gen_master.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_1/design_1_aurora_64b66b_0_0_fifo_gen_master_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_2/design_1_aurora_64b66b_0_0_fifo_gen_slave.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_0_0/ip_2/design_1_aurora_64b66b_0_0_fifo_gen_slave_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_0_0/design_1_aurora_64b66b_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_0_0/design_1_aurora_64b66b_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_0_0/design_1_aurora_64b66b_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_0/synth/design_1_aurora_64b66b_1_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_0/synth/design_1_aurora_64b66b_1_0_gt.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_1/design_1_aurora_64b66b_1_0_fifo_gen_master.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_1/design_1_aurora_64b66b_1_0_fifo_gen_master_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_2/design_1_aurora_64b66b_1_0_fifo_gen_slave.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_1_0/ip_2/design_1_aurora_64b66b_1_0_fifo_gen_slave_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_1_0/design_1_aurora_64b66b_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_1_0/design_1_aurora_64b66b_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_aurora_64b66b_1_0/design_1_aurora_64b66b_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_2_0/design_1_util_ds_buf_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_2_0/design_1_util_ds_buf_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_3_0/design_1_util_ds_buf_3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_3_0/design_1_util_ds_buf_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/ip/design_1_emax6_0_0/design_1_emax6_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/constrs_1/imports/MAP/io_ports_150M.xdc
set_property used_in_implementation false [get_files /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/constrs_1/imports/MAP/io_ports_150M.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top VU440_TOP -part xcvu440-flga2892-2-e -bufg 200 -fanout_limit 200 -directive AlternateRoutability -retiming -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef VU440_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file VU440_TOP_utilization_synth.rpt -pb VU440_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
