# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}


start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  create_project -in_memory -part xcvu440-flga2892-2-e
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.cache/wt [current_project]
  set_property parent.project_path /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.xpr [current_project]
  set_property ip_output_repo /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  add_files -quiet /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.runs/synth_1/VU440_TOP.dcp
  set_msg_config -source 4 -id {BD 41-1661} -limit 0
  set_param project.isImplRun true
  read_ip -quiet /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/ip/fpga_bram64/fpga_bram64.xci
  add_files /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/sources_1/bd/design_1/design_1.bd
  set_param project.isImplRun false
  read_xdc /home/nakashim/proj-arm64/fpga/VU440-step4000/VU440_64st.srcs/constrs_1/imports/MAP/io_ports_150M.xdc
  set_param project.isImplRun true
  link_design -top VU440_TOP -part xcvu440-flga2892-2-e
  set_param project.isImplRun false
  write_hwdef -force -file VU440_TOP.hwdef
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design -directive ExploreWithRemap
  write_checkpoint -force VU440_TOP_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file VU440_TOP_drc_opted.rpt -pb VU440_TOP_drc_opted.pb -rpx VU440_TOP_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design -directive Explore
  write_checkpoint -force VU440_TOP_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file VU440_TOP_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file VU440_TOP_utilization_placed.rpt -pb VU440_TOP_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file VU440_TOP_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step phys_opt_design
set ACTIVE_STEP phys_opt_design
set rc [catch {
  create_msg_db phys_opt_design.pb
  phys_opt_design -directive ExploreWithAggressiveHoldFix
  write_checkpoint -force VU440_TOP_physopt.dcp
  close_msg_db -file phys_opt_design.pb
} RESULT]
if {$rc} {
  step_failed phys_opt_design
  return -code error $RESULT
} else {
  end_step phys_opt_design
  unset ACTIVE_STEP 
}

  set_msg_config -source 4 -id {Route 35-39} -severity "critical warning" -new_severity warning
start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design -directive AggressiveExplore -tns_cleanup
  write_checkpoint -force VU440_TOP_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file VU440_TOP_drc_routed.rpt -pb VU440_TOP_drc_routed.pb -rpx VU440_TOP_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file VU440_TOP_methodology_drc_routed.rpt -pb VU440_TOP_methodology_drc_routed.pb -rpx VU440_TOP_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file VU440_TOP_power_routed.rpt -pb VU440_TOP_power_summary_routed.pb -rpx VU440_TOP_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file VU440_TOP_route_status.rpt -pb VU440_TOP_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file VU440_TOP_timing_summary_routed.rpt -pb VU440_TOP_timing_summary_routed.pb -rpx VU440_TOP_timing_summary_routed.rpx"
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file VU440_TOP_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file VU440_TOP_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file VU440_TOP_bus_skew_routed.rpt -pb VU440_TOP_bus_skew_routed.pb -rpx VU440_TOP_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force VU440_TOP_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step post_route_phys_opt_design
set ACTIVE_STEP post_route_phys_opt_design
set rc [catch {
  set tool_flow [get_property TOOL_FLOW [current_project]]
  if {$tool_flow eq {SDx}} {send_msg_id {101-1} {status} {Starting optional post-route physical design optimization.} }
  create_msg_db post_route_phys_opt_design.pb
  phys_opt_design -directive ExploreWithAggressiveHoldFix
  write_checkpoint -force VU440_TOP_postroute_physopt.dcp
  create_report "impl_1_post_route_phys_opt_report_timing_summary_0" "report_timing_summary -max_paths 10 -warn_on_violation -file VU440_TOP_timing_summary_postroute_physopted.rpt -pb VU440_TOP_timing_summary_postroute_physopted.pb -rpx VU440_TOP_timing_summary_postroute_physopted.rpx"
  create_report "impl_1_post_route_phys_opt_report_bus_skew_0" "report_bus_skew -warn_on_violation -file VU440_TOP_bus_skew_postroute_physopted.rpt -pb VU440_TOP_bus_skew_postroute_physopted.pb -rpx VU440_TOP_bus_skew_postroute_physopted.rpx"
  close_msg_db -file post_route_phys_opt_design.pb
  set tool_flow [get_property TOOL_FLOW [current_project]]
  if {$tool_flow eq {SDx}} {send_msg_id {101-1} {status} {Finished optional post-route physical design optimization.} }
} RESULT]
if {$rc} {
  step_failed post_route_phys_opt_design
  return -code error $RESULT
} else {
  end_step post_route_phys_opt_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  catch { write_mem_info -force VU440_TOP.mmi }
  write_bitstream -force VU440_TOP.bit -bin_file
  catch { write_sysdef -hwdef VU440_TOP.hwdef -bitfile VU440_TOP.bit -meminfo VU440_TOP.mmi -file VU440_TOP.sysdef }
  catch {write_debug_probes -quiet -force VU440_TOP}
  catch {file copy -force VU440_TOP.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

